### PR TITLE
Json Web Signature 2020 suite

### PR DESCRIPTION
**Pull request by apelt**
Hello, 
I have added [JSON Web Signature 2020](https://w3c-ccg.github.io/lds-jws2020/) signature suite which I needed in my work anyway. **Feel free to update it anyhow.** 

This implementation uses Java [Nimbus library](https://connect2id.com/products/nimbus-jose-jwt) for [JWS](https://www.rfc-editor.org/rfc/rfc7515.html) and [JWK](https://www.ietf.org/rfc/rfc7517.txt) handling.

You can test the implementation with _com.apicatalog.vc.JsonWebSignature2020Test_ where I used code from _Issuer_ and _Verifier_ Processors to properly test it. Just note that Curve secp256k1 (alg. **ES256K**) is supported on Java 8, but it is NOT supported on Java 17 (see https://connect2id.com/products/nimbus-jose-jwt/jca-algorithm-support#alg-support-table).

Cheers and thanks for this library.
Petr Apeltauer, KAPRION Technologies GmbH

### CODE REVIEW

**Comment by filip26** [comment]
Hi @apelt , thank you for the PR! Please, can you add some tests to prove that the code works as expected? Take a look at `src/test/resources/.../manifest-*.jsonld`.

**Comment by apelt** [comment]
> Hi @apelt , thank you for the PR! Please, can you add some tests to prove that the code works as expected? Take a look at `src/test/resources/.../manifest-*.jsonld`.

Hi @filip26, I have added the tests in **_JsonWebSignature2020Test_** and refactored the code. I also added _JwsIssuer_ and _JwsVerifier_ processors so I could test it all. Please feel free to change anything.

**Note:** 
 - _JwsDidKeyResolver_ did:key resolution is tested only with Ed25519/X25519 keys because method _DidKey.from(did)_ can be used only with these keys. Other keys are not available in your _com.apicatalog.multicodec.Codec_.
 - verifier tests t0002, t0004 and t0017 are skipped because JWS does not use codec encoding and it has variable length.

**Comment by apelt** [comment]
@filip26 Seems the Android build failed because it cannot find the nimbus library. Should I add it to the _pom_jre8.xml_?

**Comment by filip26** [comment]
Not sure how to properly deal with an external proof. An external proof usually means that a VC is wrapped inside a different representation than JSON. Look at current API Vc.verify/issue accepts `JsonObject` but JWS expects the proof value be externalized. I think we would have to develop some interface, VcDocument? That would be inherited by JsonVc? and JwsVc? Maybe it would be easier to build a processor dealing with an external proof on top of this library.

**Comment by filip26** [comment]
@apelt a crypto suite is detached and the library should focus solely on core VC processing and high customization. 

It's not done yet, README is missing etc. but the code works. [iron-ed25519-signature-suite](https://github.com/filip26/iron-ed25519-signature-suite)

I'm going to close this PR and I encourage you to create your own repository related to JWS and I would be happy to help you adopt the code and make reasonable changes to this library if needed. Also, your library could be listed here beside ed25519 module. 

Feel free to contact me, an email is in bio.

**Comment by apelt** [comment]
> @apelt a crypto suite is detached and the library should focus solely on core VC processing and high customization.
> 
> It's not done yet, README is missing etc. but the code works. [iron-ed25519-signature-suite](https://github.com/filip26/iron-ed25519-signature-suite)
> 
> I'm going to close this PR and I encourage you to create your own repository related to JWS and I would be happy to help you adopt the code and make reasonable changes to this library if needed. Also, your library could be listed here beside ed25519 module.
> 
> Feel free to contact me, an email is in bio.

I agree, the modularity is better this way. I am currently in time press in my job. I will add the `iron-jws2020-signature-suite` probably after the [Nimbus lib. bug](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/500/bug-unencoded-jws-payloads-rfc-7797-losing) is solved, as with the bug it is not working correctly anyway (the Nimbus library with unencoded payload option works only when using text instead of any byte array so it cannot be used for VCs now).

**Pull request closed without merging**
